baseURL = "https://gustavoborges.net/"
languageCode = "pt-br"
title = "Gustavo Borges"
theme = "hyde"

[params]
  themeColor = "theme-base-08"
  description = "Desenvolvedor de Software, goiano. Aqui você encontra meus pensamentos e posts técnicos"

[Menus]
  main = [ 
    {Name = "Início", URL = "/", weight = 1},
    {Name = "Blog", URL = "/blog", weight = 2},
    {Name = "Sobre", URL = "/sobre", weight = 3},
    {Name = "Twitter", URL = "https://twitter.com/gustavomtborges"},
    {Name = "Github", URL = "https://github.com/gustavomtborges"}
  ]