baseURL = "https://gustavoborges.net/"
languageCode = "en-us"
title = "Gustavo Borges"
theme = "hyde-hyde"

[params]
  themeColor = "theme-base-08"
[params.social]
  gravatar = "gustavo.mtborges@gmail.com"
