baseURL = "https://gustavoborges.net/"
languageCode = "pt-br"
title = "Gustavo Borges"
theme = "hyde"

[params]
  themeColor = "theme-base-08"
  description = "Desenvolvedor de Software, goiano. Um dia de cada vez"

[Menus]
  main = [ 
    {Name = "Início", URL = "/", weight = 1},
    {Name = "Blog", URL = "/blog", weight = 2},
    {Name = "CV", URL = "/cv", weight = 3}
  ]

  external = [
    {Name = "Twitter", URL = "https://twitter.com/gustavomtborges"},
    {Name = "Github", URL = "https://github.com/gustavomtborges"}
  ]